name: Update GitHub Pages

on:
  workflow_dispatch:
  push:
    branches:
      - master
jobs:
  update-gh-pages:
    name: Generate and upload new GitHub Pages
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Generate website
        uses: ldeluigi/markdown-docs@v0
        with:
          src: .
          dst: gh-pages
          icon: calendar-month
      - name: Deploy GH Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: gh-pages